[package]
name = "cetus_clmm"
edition = "2024.beta"
version = "1.0.0"
license = "MIT"
authors = ["Roberto Soares <robertosoares1985@gmail.com>", "Cetus Protocol Team"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/testnet" }

# Example of additional dependencies, adjust as per your needs
# MathLib = { git = "some_math_lib_repo", subdir = "math", rev = "testnet_version" }
# CoinUtils = { local = "../path/to/local/coin_utils" }

[addresses]
CetusClmm = "0x0c7ae833c220aa73a3643a0d508afa4ac5d50d97312ea4584e35f9eb21b9df12"  # Cetus testnet address

# Named addresses for convenience in your Move code
Sui = "0x2"
Example = "0x1234"  # Example address for testing

[dev-addresses]
CetusClmm = "0x0c7ae833c220aa73a3643a0d508afa4ac5d50d97312ea4584e35f9eb21b9df12"  # Using the same as testnet for simplicity
# If you need different addresses for local development or another test environment, change this.

[dev-dependencies]
# Example of a test dependency
# TestUtils = { local = "../path/to/test_utils" }

# Configuration for build options, if needed
[build]
options = [
    "--test",
    "--dev
